version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - VITE_WORKER_URL=http://api-proxy:8080
    depends_on:
      - api-proxy

  api-proxy:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8080:8080"
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - COOLIFY_API_TOKEN=${COOLIFY_API_TOKEN}
      - COOLIFY_URL=${COOLIFY_URL}
    volumes:
      - ./src/worker:/app/worker
    command: node dist/worker.js

  # Example of how to add more API proxies in the future:
  # github-proxy:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.worker
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - GITHUB_TOKEN=${GITHUB_TOKEN} 