version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - VITE_WORKER_URL=http://api-proxy:8080
      - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL}
    depends_on:
      - api-proxy

  api-proxy:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8081:8080"
    environment:
      - VITE_CLAUDE_API_KEY=${VITE_CLAUDE_API_KEY}
      - VITE_COOLIFY_API_TOKEN=${VITE_COOLIFY_API_TOKEN}
      - VITE_COOLIFY_URL=${VITE_COOLIFY_URL}
      - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL}
    volumes:
      - ./src/worker:/app/src/worker