name = "api-proxy"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
CLAUDE_API_KEY = "your-claude-api-key"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./src/worker.ts" 